/**
 * Emits the ABIs the rest of the repo needs, from the compiled artifacts, so the
 * web app and the indexer can never drift from what was actually deployed.
 *
 *   packages/core/src/abi/*.ts   — typed const arrays for the web app
 *   packages/indexer/abis/*.json — plain JSON for Envio's config.yaml
 *
 * The Kuru OrderBook ABI is copied from @kuru-labs/kuru-sdk when it is
 * installed, and otherwise from the local IKuruOrderBook interface, which
 * declares the same three events byte for byte.
 */
import fs from "node:fs";
import path from "node:path";
import { artifacts } from "hardhat";

const ROOT = path.resolve(__dirname, "../../..");
const CORE_ABI_DIR = path.join(ROOT, "packages/core/src/abi");
const INDEXER_ABI_DIR = path.join(ROOT, "packages/indexer/abis");

const CONTRACTS = ["CellFactory", "OutcomeToken", "MockERC20", "MockKuruOrderBook", "MockKuruRouter"];

async function main() {
  fs.mkdirSync(CORE_ABI_DIR, { recursive: true });
  fs.mkdirSync(INDEXER_ABI_DIR, { recursive: true });

  for (const name of CONTRACTS) {
    const artifact = await artifacts.readArtifact(name);
    writeAbi(name, artifact.abi);
  }

  writeAbi("KuruOrderBook", await kuruOrderBookAbi());
  writeAbi("Erc20", (await artifacts.readArtifact("MockERC20")).abi.filter(isErc20Fragment));

  console.log(`Wrote ABIs to ${CORE_ABI_DIR} and ${INDEXER_ABI_DIR}`);
}

function writeAbi(name: string, abi: unknown[]) {
  const json = JSON.stringify(abi, null, 2);
  fs.writeFileSync(path.join(INDEXER_ABI_DIR, `${name}.json`), `${json}\n`);
  fs.writeFileSync(
    path.join(CORE_ABI_DIR, `${name.charAt(0).toLowerCase()}${name.slice(1)}.ts`),
    `// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.\nexport const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${json} as const;\n`,
  );
}

/** Prefer the real Kuru ABI when the SDK is present; fall back to our interface. */
async function kuruOrderBookAbi(): Promise<unknown[]> {
  const sdkAbi = path.join(ROOT, "apps/web/node_modules/@kuru-labs/kuru-sdk/abi/OrderBook.json");
  if (fs.existsSync(sdkAbi)) {
    const parsed = JSON.parse(fs.readFileSync(sdkAbi, "utf8"));
    return Array.isArray(parsed) ? parsed : parsed.abi;
  }
  console.warn("kuru-sdk not installed; falling back to IKuruOrderBook. Run `npm install` in apps/web first.");
  return (await artifacts.readArtifact("IKuruOrderBook")).abi;
}

function isErc20Fragment(fragment: { type: string; name?: string }) {
  const keep = new Set([
    "name",
    "symbol",
    "decimals",
    "totalSupply",
    "balanceOf",
    "allowance",
    "approve",
    "transfer",
    "transferFrom",
    "Transfer",
    "Approval",
  ]);
  return fragment.name != null && keep.has(fragment.name);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
