// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.
export const cellFactoryAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "collateral_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "kuruRouter_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "settler_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "operator_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyResolved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadPrice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadWindowTimes",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GraceNotElapsed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOperator",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotResolved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotSettler",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToRedeem",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnknownWindow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WindowExists",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WindowNotClosed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAmount",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "components": [
          {
            "internalType": "uint96",
            "name": "sizePrecision",
            "type": "uint96"
          },
          {
            "internalType": "uint32",
            "name": "pricePrecision",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "tickSize",
            "type": "uint32"
          },
          {
            "internalType": "uint96",
            "name": "minSize",
            "type": "uint96"
          },
          {
            "internalType": "uint96",
            "name": "maxSize",
            "type": "uint96"
          },
          {
            "internalType": "uint256",
            "name": "takerFeeBps",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "makerFeeBps",
            "type": "uint256"
          },
          {
            "internalType": "uint96",
            "name": "kuruAmmSpread",
            "type": "uint96"
          }
        ],
        "indexed": false,
        "internalType": "struct CellFactory.MarketConfig",
        "name": "config",
        "type": "tuple"
      }
    ],
    "name": "MarketConfigUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previous",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "next",
        "type": "address"
      }
    ],
    "name": "OperatorUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferStarted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "burned",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "payout",
        "type": "uint256"
      }
    ],
    "name": "Redeemed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "SetBurned",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "SetMinted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "previous",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "next",
        "type": "uint64"
      }
    ],
    "name": "SettleGraceUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previous",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "next",
        "type": "address"
      }
    ],
    "name": "SettlerUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "underlying",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "startTs",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "endTs",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "strikeE8",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "yes",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "no",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "yesMarket",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "noMarket",
        "type": "address"
      }
    ],
    "name": "WindowCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum CellFactory.Outcome",
        "name": "outcome",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "settlePriceE8",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "settledAt",
        "type": "uint64"
      }
    ],
    "name": "WindowSettled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "voidedAt",
        "type": "uint64"
      }
    ],
    "name": "WindowVoided",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "acceptOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "burnSet",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "collateralDecimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "collateralToken",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "underlying",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "startTs",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "endTs",
        "type": "uint64"
      },
      {
        "internalType": "uint256",
        "name": "strikeE8",
        "type": "uint256"
      }
    ],
    "name": "createWindow",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "underlying",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "endTs",
        "type": "uint64"
      },
      {
        "internalType": "uint256",
        "name": "strikeE8",
        "type": "uint256"
      }
    ],
    "name": "findWindow",
    "outputs": [
      {
        "internalType": "bool",
        "name": "exists",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      }
    ],
    "name": "getWindow",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "underlying",
            "type": "bytes32"
          },
          {
            "internalType": "uint64",
            "name": "startTs",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "endTs",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "strikeE8",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "yes",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "no",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "yesMarket",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "noMarket",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "collateral",
            "type": "uint256"
          },
          {
            "internalType": "enum CellFactory.Outcome",
            "name": "outcome",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "settlePriceE8",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "settledAt",
            "type": "uint64"
          }
        ],
        "internalType": "struct CellFactory.Window",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "limit",
        "type": "uint256"
      }
    ],
    "name": "getWindows",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "underlying",
            "type": "bytes32"
          },
          {
            "internalType": "uint64",
            "name": "startTs",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "endTs",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "strikeE8",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "yes",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "no",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "yesMarket",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "noMarket",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "collateral",
            "type": "uint256"
          },
          {
            "internalType": "enum CellFactory.Outcome",
            "name": "outcome",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "settlePriceE8",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "settledAt",
            "type": "uint64"
          }
        ],
        "internalType": "struct CellFactory.Window[]",
        "name": "page",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "kuruRouter",
    "outputs": [
      {
        "internalType": "contract IKuruRouter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "marketConfig",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "sizePrecision",
        "type": "uint96"
      },
      {
        "internalType": "uint32",
        "name": "pricePrecision",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "tickSize",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "minSize",
        "type": "uint96"
      },
      {
        "internalType": "uint96",
        "name": "maxSize",
        "type": "uint96"
      },
      {
        "internalType": "uint256",
        "name": "takerFeeBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "makerFeeBps",
        "type": "uint256"
      },
      {
        "internalType": "uint96",
        "name": "kuruAmmSpread",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintSet",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "operator",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "pendingOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      }
    ],
    "name": "redeem",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "payout",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "uint96",
            "name": "sizePrecision",
            "type": "uint96"
          },
          {
            "internalType": "uint32",
            "name": "pricePrecision",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "tickSize",
            "type": "uint32"
          },
          {
            "internalType": "uint96",
            "name": "minSize",
            "type": "uint96"
          },
          {
            "internalType": "uint96",
            "name": "maxSize",
            "type": "uint96"
          },
          {
            "internalType": "uint256",
            "name": "takerFeeBps",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "makerFeeBps",
            "type": "uint256"
          },
          {
            "internalType": "uint96",
            "name": "kuruAmmSpread",
            "type": "uint96"
          }
        ],
        "internalType": "struct CellFactory.MarketConfig",
        "name": "config",
        "type": "tuple"
      }
    ],
    "name": "setMarketConfig",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "next",
        "type": "address"
      }
    ],
    "name": "setOperator",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "next",
        "type": "uint64"
      }
    ],
    "name": "setSettleGrace",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "next",
        "type": "address"
      }
    ],
    "name": "setSettler",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "settlePriceE8",
        "type": "uint256"
      }
    ],
    "name": "settle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "settleGrace",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "settler",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "windowId",
        "type": "uint256"
      }
    ],
    "name": "voidWindow",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "windowCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "underlying",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "endTs",
        "type": "uint64"
      },
      {
        "internalType": "uint256",
        "name": "strikeE8",
        "type": "uint256"
      }
    ],
    "name": "windowKey",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;
