// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.
export const kuruOrderBookAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40",
        "name": "orderId",
        "type": "uint40"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isBuy",
        "type": "bool"
      }
    ],
    "name": "OrderCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40[]",
        "name": "orderId",
        "type": "uint40[]"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OrdersCanceled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40",
        "name": "orderId",
        "type": "uint40"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "makerAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isBuy",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "updatedSize",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "takerAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "txOrigin",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "filledSize",
        "type": "uint96"
      }
    ],
    "name": "Trade",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "_price",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "bool",
        "name": "_postOnly",
        "type": "bool"
      }
    ],
    "name": "addBuyOrder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "_price",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "bool",
        "name": "_postOnly",
        "type": "bool"
      }
    ],
    "name": "addSellOrder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint40[]",
        "name": "_orderIds",
        "type": "uint40[]"
      }
    ],
    "name": "batchCancelOrders",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32[]",
        "name": "buyPrices",
        "type": "uint32[]"
      },
      {
        "internalType": "uint96[]",
        "name": "buySizes",
        "type": "uint96[]"
      },
      {
        "internalType": "uint32[]",
        "name": "sellPrices",
        "type": "uint32[]"
      },
      {
        "internalType": "uint96[]",
        "name": "sellSizes",
        "type": "uint96[]"
      },
      {
        "internalType": "uint40[]",
        "name": "orderIdsToCancel",
        "type": "uint40[]"
      },
      {
        "internalType": "bool",
        "name": "postOnly",
        "type": "bool"
      }
    ],
    "name": "batchUpdate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "bestBidAsk",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getL2Book",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
