// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.
export const mockKuruRouterAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "baseAsset",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "quoteAsset",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "market",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "vaultAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "pricePrecision",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "sizePrecision",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "tickSize",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "minSize",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "maxSize",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "takerFeeBps",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "makerFeeBps",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "kuruAmmSpread",
        "type": "uint96"
      }
    ],
    "name": "MarketRegistered",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      },
      {
        "internalType": "address",
        "name": "_baseAssetAddress",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_quoteAssetAddress",
        "type": "address"
      },
      {
        "internalType": "uint96",
        "name": "_sizePrecision",
        "type": "uint96"
      },
      {
        "internalType": "uint32",
        "name": "_pricePrecision",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "_tickSize",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "_minSize",
        "type": "uint96"
      },
      {
        "internalType": "uint96",
        "name": "_maxSize",
        "type": "uint96"
      },
      {
        "internalType": "uint256",
        "name": "_takerFeeBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_makerFeeBps",
        "type": "uint256"
      },
      {
        "internalType": "uint96",
        "name": "_kuruAmmSpread",
        "type": "uint96"
      }
    ],
    "name": "deployProxy",
    "outputs": [
      {
        "internalType": "address",
        "name": "proxy",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "marketCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "markets",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
