// Generated by packages/contracts/scripts/export-abi.ts. Do not edit.
export const mockKuruOrderBookAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "baseAsset_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "quoteAsset_",
        "type": "address"
      },
      {
        "internalType": "uint96",
        "name": "sizePrecision_",
        "type": "uint96"
      },
      {
        "internalType": "uint32",
        "name": "pricePrecision_",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "tickSize_",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "minSize_",
        "type": "uint96"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "BadTick",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BelowMinSize",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PostOnlyCrossed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40",
        "name": "orderId",
        "type": "uint40"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isBuy",
        "type": "bool"
      }
    ],
    "name": "OrderCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40[]",
        "name": "orderId",
        "type": "uint40[]"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OrdersCanceled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint40",
        "name": "orderId",
        "type": "uint40"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "makerAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isBuy",
        "type": "bool"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "updatedSize",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "takerAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "txOrigin",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "filledSize",
        "type": "uint96"
      }
    ],
    "name": "Trade",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "bool",
        "name": "postOnly",
        "type": "bool"
      }
    ],
    "name": "addBuyOrder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      },
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "bool",
        "name": "postOnly",
        "type": "bool"
      }
    ],
    "name": "addSellOrder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      }
    ],
    "name": "baseAmount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "baseAsset",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint40[]",
        "name": "orderIds",
        "type": "uint40[]"
      }
    ],
    "name": "batchCancelOrders",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "bestBidAsk",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "bid",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "ask",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "minSize",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "openOrderIds",
    "outputs": [
      {
        "internalType": "uint40[]",
        "name": "",
        "type": "uint40[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "orderIdCounter",
    "outputs": [
      {
        "internalType": "uint40",
        "name": "",
        "type": "uint40"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint40",
        "name": "",
        "type": "uint40"
      }
    ],
    "name": "orders",
    "outputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      },
      {
        "internalType": "bool",
        "name": "isBuy",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "alive",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "pricePrecision",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint96",
        "name": "size",
        "type": "uint96"
      },
      {
        "internalType": "uint32",
        "name": "price",
        "type": "uint32"
      }
    ],
    "name": "quoteAmount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "quoteAsset",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "sizePrecision",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "tickSize",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
